algoritmo "Salario"
// Função :
// Autor :
// Data : 06/05/2013
// Seção de Declarações 
var
  horas : inteiro
  valor : real
  salario : real


inicio
// Seção de Comandos 
escreval("Entre com o valor do salario por hora:")
leia(valor)
escreval("Entre com o valor de horas trabalhada:")
leia(horas)

salario <- horas*valor

escreval("O valor do salario é:" ,salario)

fimalgoritmo
